okta:
  oauth2:
    client-id: 0oah3u9c73C3n5hR80h7
    client-secret: cPYXSumg2PC1jk_lnoPqEq9TmwXigcw8jPo
    issuer: https://dev-737523.oktapreview.com/oauth2/default
spring:
  profiles:
    active: @spring.profiles.active@